### ISSUE TITLE
Risc0 Benchmark incompatible client version

### ISSUE THREAD

**Issue by nhlita** [lita-xyz/benchmarks#1]
When trying to run the Risc0 fibonacci benchmark I get the following error:
```
cargo run --release
   Compiling methods v0.1.0 (/home/nhlita/lita/benchmarks/fibonacci/risc0/methods)
fib: Starting build for riscv32im-risc0-zkvm-elf: methods(build)                                                                                                                   
fib:     Finished `release` profile [optimized] target(s) in 0.05s
   Compiling host v0.1.0 (/home/nhlita/lita/benchmarks/fibonacci/risc0/host)
    Finished `release` profile [optimized + debuginfo] target(s) in 41.04s
     Running `target/release/host`
thread 'main' panicked at risc0/r0vm/src/lib.rs:192:18:
called `Result::unwrap()` on an `Err` value: incompatible client version: 0.21.0, server version: 1.0.1
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at host/src/main.rs:35:10:
called `Result::unwrap()` on an `Err` value: failed to fill whole buffer
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
As it says, it doesn't like the version of Risc0 installed so I had to install v0.21.0 to get it to run. Will we have to bump the version expected by the code manually each time there's a new Risc0 version? I was hoping we could just pull the latest and benchmark that each time rather than potentially testing out of date versions.

**Comment by thealmarty** [comment]
Hm that's strange....this is what I got:
```
~/code/lita/benchmarks/fibonacci/risc0$ RISC0_DEV_MODE=0 cargo run --release
   Compiling protobuf-src v1.1.0+21.5
   Compiling tokio-util v0.7.11
   Compiling tokio-rustls v0.24.1
   Compiling ark-ec v0.4.2
   Compiling methods v0.1.0 (/home/marty/code/lita/benchmarks/fibonacci/risc0/methods)
error: failed to run custom build command for `methods v0.1.0 (/home/marty/code/lita/benchmarks/fibonacci/risc0/methods)`

Caused by:
  process didn't exit successfully: `/home/marty/code/lita/benchmarks/fibonacci/risc0/target/release/build/methods-ac7434c0d0ad176d/build-script-build` (exit status: 255)
  --- stderr
  The 'risc0' toolchain could not be found.
  To install the risc0 toolchain, use cargo-risczero.
  For example:
    cargo binstall cargo-risczero
    cargo risczero install
warning: build failed, waiting for other jobs to finish...
```

**Comment by thealmarty** [comment]
I think I removed some of the generated files during re-org. Sorry about that. Try follow [this guide](https://dev.risczero.com/api/zkvm/quickstart) and update the project code to what we have here.

**Comment by thealmarty** [comment]
Or maybe revert some of [this commit](https://github.com/lita-xyz/benchmarks/commit/9c3447c1a8513a49057087b2f3dfe84bac6d510f).

**Comment by nhlita** [comment]
`The 'risc0' toolchain could not be found.`
I think maybe you don't have risc0 installed or available? Does `rustup show ` include `risc0`  for you?

I bumped the cargo versions of `risc0-build` to accept 1.0.1 and above. The fibonacci should now run ok until an API change breaks it in the future (code update was needed this time in addition to the version bump). Maintaining these looks like it going to be a chore, wonder if we should revisit our desire to be benchmarking all our competition..

I also ran into the issue you had with the program recompiling every time it gets run, can't find a way to fix that.

**Comment by thealmarty** [comment]
> `The 'risc0' toolchain could not be found.` I think maybe you don't have risc0 installed or available? Does `rustup show ` include `risc0` for you?
>

Yeah I think it's because I deleted a bunch of the compiled code and didn't rebuilt, but it seems there's still problems after building.
 
> I bumped the cargo versions of `risc0-build` to accept 1.0.1 and above. The fibonacci should now run ok until an API change breaks it in the future (code update was needed this time in addition to the version bump). Maintaining these looks like it going to be a chore, wonder if we should revisit our desire to be benchmarking all our competition..
> 

Glad you figured it out. Yeah keep us posted and we can see how it goes.

> I also ran into the issue you had with the program recompiling every time it gets run, can't find a way to fix that.

Yes, please discard the first run in the stats for all benchmarks, because of this.
